### ISSUE TITLE
Cocoapods with NZCircularImageView

### ISSUE THREAD

**Issue by pangers** [NZN/NZCircularImageView#8]
Hi, 

I am trying to use Cocoapods with NZCircularImageView in XCode 6.1.1 swift project but I am getting a number of errors regarding the import statements
In UIImageView+UIActivityIndicatorForSDWebImage.h:
#import "UIImageView+WebCache.h"
#import "SDImageCache.h"
#import "UIImageView+UIActivityIndicatorForSDWebImage.h"
error is "Include of non-modular header inside framework module 'UIActivityIndicator_for_SDWebImage.UIImageView_UIActivityIndicatorForSDWebImage"

and in NZCircularImageView.h
#import "UIImageView+UIActivityIndicatorForSDWebImage.h"
error is "Could not build module 'UIActivityIndicator_for_SDWebImage".

Would you have any idea about how to fix this?

**Comment by MHaroonBaig** [comment]
Use the pre-release version of the CocoaPods.

**Comment by fatuhoku** [comment]
I still get the error  `Could not build module 'UIActivityIndicator_for_SDWebImage'` after I switch on `use_frameworks!` in my Podfile. What's going on?
